markdown: kramdown

theme: jekyll-theme-minimal
logo: assets/logo.png
title: Optimizaci√≥n de operaciones
description: Contenidos de la materia

markdown_extensions:
  - attr_list

plugins:
- search
- open-in-new-tab